Fix Compile Error: str Naming
This fixes a build error compiling with nvcc/7.5
causing a
```
./include/pybind11/pytypes.h: In member function ‘pybind11::str pybind11::handle::str() const’:
./include/pybind11/pytypes.h:292:8: error: expected primary-expression before ‘class’
     return pybind11::str(str, false);
        ^
./include/pybind11/pytypes.h:292:8: error: expected ‘;’ before ‘class’
./include/pybind11/pytypes.h:292:8: error: expected primary-expression before ‘class’
```