Add test that exposes breakage:
```
g++ -o pybind11/tests/test_modules.os -c -std=c++20 -fPIC -fvisibility=hidden -O0 -g -Wall -Wextra -Wconversion -Wcast-qual -Wdeprecated -Wundef -Wnon-virtual-dtor -Wunused-result -Werror -funsigned-char -Wpedantic -isystem /wrk/cpython_installs/v3.14.2_df793163d58_default/include/python3.14 -isystem /usr/include/eigen3 -DPYBIND11_SMART_HOLDER_PADDING_ON -DPYBIND11_STRICT_ASSERTS_CLASS_HOLDER_VS_TYPE_CASTER_MIX -DPYBIND11_ENABLE_TYPE_CASTER_ODR_GUARD_IF_AVAILABLE -DPYBIND11_TEST_BOOST -Ipybind11/include -I/wrk/forked/pybind11/include -I/wrk/clone/pybind11/include /wrk/forked/pybind11/tests/test_modules.cpp
In file included from /wrk/forked/pybind11/include/pybind11/eval.h:14,
                 from /wrk/forked/pybind11/tests/pybind11_tests.h:3,
                 from /wrk/forked/pybind11/tests/constructor_stats.h:68,
                 from /wrk/forked/pybind11/tests/test_modules.cpp:11:
/wrk/forked/pybind11/include/pybind11/pybind11.h: In instantiation of ‘pybind11::module_& pybind11::module_::def(const std::string&, Func&&, const Extra& ...) [with Func = test_submodule_modules(pybind11::module_&)::<lambda(int)>; Extra = {pybind11::arg}; std::string = std::__cxx11::basic_string<char>]’:
/wrk/forked/pybind11/tests/test_modules.cpp:129:21:   required from here
/wrk/forked/pybind11/include/pybind11/pybind11.h:1549:57: error: binding reference of type ‘std::remove_reference<pybind11::arg>::type&’ {aka ‘pybind11::arg&’} to ‘const pybind11::arg’ discards qualifiers
 1549 |         return def(name_.c_str(), f, std::forward<Extra>(extra)...);
      |                                      ~~~~~~~~~~~~~~~~~~~^~~~~~~
In file included from /usr/include/c++/13/bits/stl_pair.h:61,
                 from /usr/include/c++/13/bits/stl_algobase.h:64,
                 from /usr/include/c++/13/bits/specfun.h:43,
                 from /usr/include/c++/13/cmath:3699,
                 from /usr/include/c++/13/math.h:36,
                 from /wrk/cpython_installs/v3.14.2_df793163d58_default/include/python3.14/Python.h:23,
                 from /wrk/forked/pybind11/include/pybind11/conduit/wrap_include_python_h.h:44,
                 from /wrk/forked/pybind11/include/pybind11/detail/common.h:12,
                 from /wrk/forked/pybind11/include/pybind11/attr.h:13,
                 from /wrk/forked/pybind11/include/pybind11/detail/class.h:12,
                 from /wrk/forked/pybind11/include/pybind11/pybind11.h:12:
/usr/include/c++/13/bits/move.h:70:56: note:   initializing argument 1 of ‘constexpr _Tp&& std::forward(typename remove_reference<_Functor>::type&) [with _Tp = pybind11::arg; typename remove_reference<_Functor>::type = pybind11::arg]’
   70 |     forward(typename std::remove_reference<_Tp>::type& __t) noexcept
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```